import type { LanguageCode } from '@everynews/schema'

export const LANGUAGE_TITLE: Record<LanguageCode, string> = {
  af: 'Bondige Interessante Titel',
  ak: 'Teatea Nanso Yɛdɛ Titiriw',
  am: 'አጭር አስደሳች ርዕስ',
  ar: 'عنوان موجز شيق',
  as: 'সংক্ষিপ্ত কিন্তু ৰুচিকৰ শিৰোনাম',
  ay: 'Título Conciso e Interesante',
  az: 'Qısa Maraqlı Başlıq',
  ba: 'Ҡыҫҡа ҡыҙыҡлы башлыҡ',
  be: 'Кароткі Цікавы Загаловак',
  bg: 'Кратко Интересно Заглавие',
  bho: 'संछिप्त रोचक शीर्षक',
  bm: 'Titre Concis et Intéressant',
  bn: 'সংক্ষিপ্ত আকর্ষণীয় শিরোনাম',
  bo: 'བསྡུས་པའི་སྤྲོ་སྣང་ཅན་མགོ་མིང་',
  bs: 'Kratak Zanimljiv Naslov',
  ca: 'Títol Concís i Interessant',
  ceb: 'Mubo nga Makapainteres nga Ulohan',
  ckb: 'سەرنەوی نزم و دڵخواز',
  co: 'Titulu Concisu è Interessante',
  cs: 'Stručný Zajímavý Titulek',
  cy: 'Teitl Byr Diddorol',
  da: 'Kort Interessant Titel',
  de: 'Prägnanter Interessanter Titel',
  doi: 'संक्षिप्त रोचक शीर्षक',
  dv: 'ސާވާން މަހަށް ރަނގަޅު ޓައިޓަލް',
  ee: 'Titri Kagbɔsia Lɔlɔ̃',
  el: 'Σύντοχος Ενδιαφέρων Τίτλος',
  en: 'Succinct Interesting Title',
  eo: 'Konciza Interesa Titolo',
  es: 'Título Conciso e Interesante',
  et: 'Lühike Huvitav Pealkiri',
  eu: 'Izenburu Labur Interesgarria',
  fa: 'عنوان مختصر و جالب',
  fi: 'Ytimekäs Mielenkiintoinen Otsikko',
  fil: 'Maikling Kawili-wiling Pamagat',
  fj: 'Uluvatu Lekaleka Dau Yaga',
  fo: 'Stutt Áhugavert Heiti',
  fr: 'Titre Concis et Intéressant',
  fy: 'Koarte Ynteressante Titel',
  ga: 'Teideal Gonta Suimiúil',
  gd: 'Tiotal Goirid Inntinneach',
  gl: 'Título Conciso e Interesante',
  gn: "Téra Mbyky Ha Ipya'e",
  gom: 'संक्षिप्त रोचक शिर्षक',
  gu: 'સંક્ષિપ્ત રસપ્રદ શીર્ષક',
  ha: "Take Gajere Mai Ban Sha'awa",
  haw: 'Po‘omaka Pōkole ʻIke Pānaʻi',
  he: 'כותרת תמציתית ומעניינת',
  hi: 'संक्षिप्त दिलचस्प शीर्षक',
  hmn: 'Lub Ncauj Lus Luv Nthuav',
  hr: 'Kratak Zanimljiv Naslov',
  hsb: 'Króćki Zajimawy Tytuł',
  ht: 'Tit Konse Enteresan',
  hu: 'Tömör Érdekes Cím',
  hy: 'Կարճ Հետաքրքիր Վերնագիր',
  id: 'Judul Singkat Menarik',
  ig: 'Aha Isiokwu Mkpirikpi Dị Mma',
  ikt: 'Succinct Interesting Title',
  ilo: 'Ababa Ngem Makadaniw a Titulo',
  is: 'Stutt Áhugavert Heiti',
  it: 'Titolo Conciso e Interessante',
  iu: 'ᓴᓇᙱᑐᖅ ᓯᒃᑲᑦ ᓯᓚᖅ',
  ja: '簡潔で興味深いタイトル',
  jv: 'Irah-Irah Cekak Lan Narik Kawigaten',
  ka: 'შემოკლებული საინტერესო სათაური',
  kk: 'Қысқа Қызықты Тақырып',
  km: 'ចំណងជើងខ្លីគួរឱ្យចាប់អារម្មណ៍',
  kmr: 'Sernavê Kurt û Balkêş',
  kn: 'ಸಂಕ್ಷಿಪ್ತ ಆಸಕ್ತಿಕರ ಶೀರ್ಷಿಕೆ',
  ko: '간결하지만 흥미로운 제목',
  kri: 'Short En Interestin Titul',
  ku: 'Sernavê Kurt û Balkêş',
  ky: 'Кыска Кызыктуу Аталыш',
  la: 'Titulus Concisus et Iucundus',
  lb: 'Kuerzen Interessante Titel',
  lg: 'Omutwe Ogupakase Ogwokunyumira',
  ln: 'Titre Mokuse Ya Kosepelisa',
  lo: 'ຫົວຂໍ້ສັ້ນນ່າສົນໃຈ',
  lt: 'Trumpas Įdomus Pavadinimas',
  lus: 'Thiltih Hnuaia Hmingchhiar',
  lv: 'Īss Interesants Virsraksts',
  mai: 'संक्षिप्त रोचक शीर्षक',
  mg: 'Lohateny Fohy Mahaliana',
  mi: 'Taitara Poto Pārekareka',
  mk: 'Краток Интересен Наслов',
  ml: 'സംക്ഷിപ്തവും ആകര്‍ഷകവുമായ ശീർഷകം',
  mn: 'Товчхон Сонирхолтой Гарчиг',
  mni: 'ꯀꯅꯤꯃꯥ ꯄꯥꯔ ꯌꯥꯝꯅꯥ ꯇꯤꯂꯦ',
  mr: 'संक्षिप्त रोचक शीर्षक',
  ms: 'Tajuk Ringkas Menarik',
  mt: 'Titlu Konċiż u Interessanti',
  mww: 'Lub Ncauj Lus Luv Nyiam',
  my: 'အကျဉ်းချုပ် စိတ်ဝင်စားဖွယ် ခေါင်းစဉ်',
  nb: 'Kort Interessant Tittel',
  ne: 'संक्षिप्त रोचक शीर्षक',
  nl: 'Bondige Interessante Titel',
  nso: 'Succinct Interesting Title',
  ny: 'Mutu Wachidule Wosangalatsa',
  om: 'Mata Dure Gaarii Gabaabaa',
  or: 'ସଂକ୍ଷିପ୍ତ ରୋଚକ ଶୀର୍ଷକ',
  otq: 'Título Conciso e Interesante',
  pa: 'ਸੰਖੇਪ ਦਿਲਚਸਪ ਸਿਰਲੇਖ',
  pl: 'Zwięzły Interesujący Tytuł',
  prs: 'عنوان مختصر و جالب',
  ps: 'لنډ خو په زړه پورې سرلیک',
  pt: 'Título Sucinto e Interessante',
  qu: 'Título Conciso e Interesante',
  ro: 'Titlu Scurt și Interesant',
  ru: 'Краткий Интересный Заголовок',
  rw: 'Umutwe Mugufi Ushishikaje',
  sa: 'संक्षिप्तः रोचकः शीर्षकः',
  sd: 'مختصر دلچسپ عنوان',
  si: 'සංක්ෂිප්ත රසවත් මාතෘකාව',
  sk: 'Stručný Zaujímavý Názov',
  sl: 'Kratek Zanimiv Naslov',
  sm: 'Ulu Faapuupuu Manuia',
  sn: 'Musoro Pfupi Unonakidza',
  so: 'Cinwaan Gaaban Oo Xiiso Leh',
  sq: 'Titull i Shkurtër Interesant',
  sr: 'Кратак Занимљив Наслов',
  st: 'Sehlooho se Khutshwane se Khahla',
  su: 'Judul Pondok Pikaresepeun',
  sv: 'Koncis Intressant Titel',
  sw: 'Kichwa Kifupi Kinachovutia',
  ta: 'சுருங்கிய வினோதமான தலைப்பு',
  te: 'సంక్షిప్తంగా ఆసక్తికర శీర్షిక',
  tg: 'Унвони Мухтасар ва Ҷолиб',
  th: 'หัวข้อสั้นที่น่าสนใจ',
  ti: 'መለያየት አጭር አስደሳች አርእስት',
  tk: 'Gysga Gyzykly At',
  tl: 'Maikling Kawili-wiling Pamagat',
  to: "Ulutala Nounou Faka'óngorā",
  tr: 'Kısa İlginç Başlık',
  ts: 'Xichavo Xi Nghariwile Kwalayeka',
  tt: 'Җитди Кызыклы Исем',
  ty: 'Tetera Poto Māere',
  ug: 'قىسقا قىززىقارلىق باش تېما',
  uk: 'Стислий Цікавий Заголовок',
  ur: 'مختصر دلچسپ عنوان',
  uz: 'Qisqa Qiziqarli Sarlavha',
  vi: 'Tiêu Đề Ngắn Gọn Hấp Dẫn',
  xh: 'Isihloko Esifutshane Esinomdla',
  yi: 'קורצער אינטערעסאנטער טייטל',
  yo: 'Ákọlé Kúkúrú Tó Ní Àánú',
  yua: 'Título Conciso e Interesante',
  yue: '精簡有趣嘅標題',
  'zh-CN': '简洁有趣的标题',
  'zh-TW': '簡潔有趣的標題',
  zu: 'Isihloko Esifishane Esithakazelisayo',
}

export const LANGUAGE_KEYFINDING: Record<LanguageCode, string> = {
  af: 'Belangrikste Bevinding',
  ak: 'Asɛm Titiriw',
  am: 'ቁልፍ ውጤት',
  ar: 'نتيجة رئيسية',
  as: 'মূল আৱিষ্কাৰ',
  ay: 'Hallazgo Clave',
  az: 'Əsas Tapıntı',
  ba: 'Төп асыш',
  be: 'Ключавая Выснова',
  bg: 'Ключово Откритие',
  bho: 'मुख्य खोज',
  bm: 'Constat Clé',
  bn: 'মূল অনুসন্ধান',
  bo: 'གཙོ་བོའི་ཐོབ་འབྲས་',
  bs: 'Ključni Nalaz',
  ca: 'Troballa Clau',
  ceb: 'Pangunang Pagkakaplag',
  ckb: 'دۆزینه‌ سەرەكی',
  co: 'Scuperta Chjave',
  cs: 'Klíčový Nález',
  cy: 'Canfyddiad Allweddol',
  da: 'Nøglefund',
  de: 'Zentrales Ergebnis',
  doi: 'मुख्य खोज',
  dv: 'ކީ ފާނޑިންގް',
  ee: 'Ɖetsɔ Yoyi',
  el: 'Κύριο Εύρημα',
  en: 'Key Finding',
  eo: 'Ĉefa Trovaĵo',
  es: 'Hallazgo Clave',
  et: 'Peamine Tulem',
  eu: 'Aurkikuntza Gakoa',
  fa: 'یافته کلیدی',
  fi: 'Keskeinen Löydös',
  fil: 'Pangunahing Natuklasan',
  fj: 'Kila Bibi',
  fo: 'Lykilfunnur',
  fr: 'Constat Clé',
  fy: 'Haadfûn',
  ga: 'Príomh-Aimsiú',
  gd: 'Prìomh Lorg',
  gl: 'Atopado Clave',
  gn: 'Jeheka Guasu',
  gom: 'मुख्य निष्कर्ष',
  gu: 'મુખ્ય શોધ',
  ha: 'Muhimmin Gano',
  haw: 'ʻIke Kūʻiʻo Nui',
  he: 'ממצא מרכזי',
  hi: 'मुख्य निष्कर्ष',
  hmn: 'Kev Tshawb Pom Tseem Ceeb',
  hr: 'Ključni Nalaz',
  hsb: 'Klucowy Namołk',
  ht: 'Dekouvèt Kle',
  hu: 'Kulcsmegállapítás',
  hy: 'Հիմնական Բացահայտում',
  id: 'Temuan Utama',
  ig: 'Nchọpụta Isi',
  ikt: 'Key Finding',
  ilo: 'Pangunek Nga Nadiskubre',
  is: 'Lykilniðurstaða',
  it: 'Risultato Chiave',
  iu: 'ᑭᓯᐊᖅ ᐱᔭᖅᑯᑦ',
  ja: '主要な発見',
  jv: 'Panemuan Kunci',
  ka: 'ძირითადი აღმოჩენა',
  kk: 'Негізгі Тұжырым',
  km: 'ការរកឃើញសំខាន់',
  kmr: 'Dîtinê Serekî',
  kn: 'ಮುಖ್ಯ ಕಂಡುಹಿಡಿತ',
  ko: '중요 쟁점',
  kri: 'Key Fainin',
  ku: 'Dîtinê Serekî',
  ky: 'Негизги Табылга',
  la: 'Inventum Praecipuum',
  lb: 'Schlësselerkenntnis',
  lg: "Okuzuula Okw'Enkomeredde",
  ln: 'Kokuta Ya Motuya',
  lo: 'ຜົນການຄົ້ນພົບຫຼັກ',
  lt: 'Pagrindinė Išvada',
  lus: 'Thil Hrilhfiah',
  lv: 'Galvenais Atklājums',
  mai: 'प्रमुख खोज',
  mg: 'Fahitana Fototra',
  mi: 'Kitenga Matua',
  mk: 'Клучно Откритие',
  ml: 'പ്രധാന കണ്ടെത്തൽ',
  mn: 'Гол Нээлт',
  mni: 'ꯑꯃꯁꯨꯡ ꯑꯁꯤꯡ ꯐꯣꯗꯤ',
  mr: 'मुख्य शोध',
  ms: 'Penemuan Utama',
  mt: 'Skoperta Ewlenija',
  mww: 'Khoom Txheeb Zaj Tseem Ceeb',
  my: 'အဓိက ရှာဖွေတွေ့ရှိချက်',
  nb: 'Hovedfunn',
  ne: 'मुख्य पत्ता लगाउने तथ्य',
  nl: 'Belangrijkste Bevinding',
  nso: 'Key Finding',
  ny: 'Kupeza Kofunika',
  om: 'Gabaasa Ijo',
  or: 'ମୁଖ୍ୟ ଆବିଷ୍କାର',
  otq: 'Hallazgo Clave',
  pa: 'ਮੁੱਖ ਖੋਜ',
  pl: 'Kluczowe Odkrycie',
  prs: 'یافته کلیدی',
  ps: 'کلیدي موندنه',
  pt: 'Conclusão Principal',
  qu: 'Hallazgo Clave',
  ro: 'Constatare Cheie',
  ru: 'Ключевое Открытие',
  rw: "Iby'ingenzi Byabonetse",
  sa: 'मुख्य निष्कर्षः',
  sd: 'مکي دريافت',
  si: 'ප්‍රධාන සොයාගැනීම',
  sk: 'Kľúčové Zistenie',
  sl: 'Ključna Ugotovitev',
  sm: 'Sailiga Autu',
  sn: 'Kuwanika Kukuru',
  so: 'Helitaanka Muhiimka ah',
  sq: 'Gjetje Kryesore',
  sr: 'Кључни Налаз',
  st: 'Tswelopelo ya Bohlokwa',
  su: 'Pangmanggih Konci',
  sv: 'Viktigt Fynd',
  sw: 'Ugunduzi Muhimu',
  ta: 'முக்கிய கண்டுபிடிப்பு',
  te: 'ప్రధాన కనుగొనడం',
  tg: 'Хулосаи Калидӣ',
  th: 'ข้อค้นพบสำคัญ',
  ti: 'ዋና ግኝት',
  tk: 'Esasy Tapyndy',
  tl: 'Pangunahing Natuklasan',
  to: 'ʻIloʻanga Tefito',
  tr: 'Temel Bulgular',
  ts: 'Ku Kuma Ka Nkoka',
  tt: 'Төп Таба',
  ty: "Fa'atanoraa Faufaa",
  ug: 'مۇھىم تەپىلمە',
  uk: 'Ключове Відкриття',
  ur: 'اہم نتیجہ',
  uz: 'Asosiy Topilma',
  vi: 'Phát Hiện Chính',
  xh: 'Ukufumanisa Okubalulekileyo',
  yi: 'הויפּט געפינען',
  yo: 'Àwárí Kókó',
  yua: 'Hallazgo Clave',
  yue: '關鍵發現',
  'zh-CN': '关键发现',
  'zh-TW': '關鍵發現',
  zu: 'Okutholakele Okubalulekile',
}
