name: Hourly

concurrency: hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
      - name: Run cron job
        run: bun run cron/index.ts
        env:
          NODE_ENV: production
          BRIGHTDATA_API_KEY: ${{ secrets.BRIGHTDATA_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXASEARCH_API_KEY: ${{ secrets.EXASEARCH_API_KEY }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          PLUNK_API_KEY: ${{ secrets.PLUNK_API_KEY }}
          LOGSNAG_PROJECT_TOKEN: ${{ secrets.LOGSNAG_PROJECT_TOKEN }}
          LOGSNAG_PROJECT_ID: ${{ secrets.LOGSNAG_PROJECT_ID }}